name: cmd3
base: core18 # the base snap is the execution environment for this snap
version: '0.0.4'
summary: "A terminal that automates commands by recording what you type to build scripts"
description: |
  I do a lot on the command line, so I started working on a custom terminal emulator of my own that
  automates things I do as much as possible.  This terminal was built by a programmer for programmers.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
apps:
  part-os-release:
    command: scripts/cmd3
parts:
  cmd3:
    plugin: gradle
    source: https://github.com/bsautner/cmd3.git
    source-type: git
    gradle-options: []   # suppress running of tests and run the war task
    gradle-output-dir: build/libs
  part-os-release:
      plugin: dump
      source: .
      organize:
        cmd3: scripts/



