name: cmd3
version: "0.0.8"
summary: A Java Galaxian clone
description: |
  JGalaxian is a Java-based Galaxian clone.
confinement: devmode
grade: devel
base: core18

apps:
  jgalaxian:
    command: usr/bin/jg-snap
    environment:

      # Needed for fontconfig
#      XDG_DATA_HOME: ${SNAP}/usr/share
#      FONTCONFIG_PATH: ${SNAP}/etc/fonts/config.d
#      FONTCONFIG_FILE: ${SNAP}/etc/fonts/fonts.conf
    plugs: [x11,pulseaudio,audio-playback]
    #extensions: [ gnome-3-28 ]


parts:


  jgalaxian:
    plugin: gradle
    source-type: local
    source: .
    build-packages:
      - openjdk-11-jdk
    stage-packages:
      - openjdk-11-jdk
      - x11-utils
    organize:
      ${SNAPCRAFT_PART_BUILD}/jg-snap: usr/bin/jg-snap




